/*!
 * @file
 * @brief Placeholder header for HA discovery configuration.
 *
 * All ERD values are published as hex at the MQTT level.
 * String conversion is handled at the HA discovery level.
 *
 * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.
 */

// =============================================================================
// MODULE GOAL
// =============================================================================
// Goal: Provide minimal header for compatibility.
//
// Note: The string ERD list was removed; all ERDs are published as hex.
//       String conversion is handled at the HA discovery level.
// =============================================================================

#ifndef HA_DISCOVERY_CONFIG_H
#define HA_DISCOVERY_CONFIG_H

#include <stdint.h>

#endif
