#!/usr/bin/env python3
"""
Script to compress HA discovery JSONL files into C byte arrays.

Reads each JSONL file from ha_discovery/, compresses with zlib,
and outputs components/geappliances_bridge/ha_discovery_data.h
with C const uint8_t arrays and length constants.

Each category is declared as:
  const uint8_t ha_discovery_<category>[];
  const size_t ha_discovery_<category>_len;
"""

import json
import sys
import zlib
from pathlib import Path


# Category files that should be included
CATEGORIES = [
    "common",
    "refrigeration",
    "laundry",
    "dishwasher",
    "waterheater",
    "range",
    "airconditioning",
    "waterfilter",
    "smallappliance",
    "energy",
]


def category_to_cpp_name(category: str) -> str:
    """Convert category name to valid C++ identifier."""
    return category.lower()


def compress_jsonl(path: Path) -> bytes:
    """Read a JSONL file and compress its contents with zlib."""
    with open(path, 'rb') as f:
        data = f.read()
    return zlib.compress(data, level=9)


def bytes_to_c_array(data: bytes, indent: int = 2) -> str:
    """Convert bytes to a C array string."""
    lines = []
    indent_str = ' ' * indent
    # Group bytes into rows of 16
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        comma = ',' if i + 16 < len(data) else ''
        lines.append(f'{indent_str}{hex_values}{comma}')
    return '\n'.join(lines)


def generate_header(input_dir: Path) -> str:
    """Generate the complete ha_discovery_data.h header file."""
    lines = []
    lines.append('/*!')
    lines.append(' * @file')
    lines.append(' * @brief Compressed Home Assistant MQTT Discovery entity definitions.')
    lines.append(' *')
    lines.append(' * This file is auto-generated from ha_discovery/*.jsonl files.')
    lines.append(' * Do not edit this file manually. Run scripts/compress_ha_discovery.py to regenerate.')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef HA_DISCOVERY_DATA_H')
    lines.append('#define HA_DISCOVERY_DATA_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('#include <stddef.h>')
    lines.append('')

    for category in CATEGORIES:
        jsonl_path = input_dir / f'{category}.jsonl'
        if not jsonl_path.exists():
            print(f"Warning: {jsonl_path} not found, skipping", file=sys.stderr)
            continue

        compressed = compress_jsonl(jsonl_path)
        cpp_name = category_to_cpp_name(category)

        lines.append(f'// {category}.jsonl (compressed: {len(compressed)} bytes from {jsonl_path.stat().st_size} bytes)')
        lines.append(f'const uint8_t ha_discovery_{cpp_name}[] = {{')
        lines.append(bytes_to_c_array(compressed))
        lines.append('};')
        lines.append(f'const size_t ha_discovery_{cpp_name}_len = {len(compressed)};')
        lines.append('')

    lines.append('#endif')
    lines.append('')

    return '\n'.join(lines)


def main():
    """Main entry point for the script."""
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    input_dir = repo_root / 'ha_discovery'
    output_file = repo_root / 'components' / 'geappliances_bridge' / 'ha_discovery_data.h'

    if not input_dir.exists():
        print(f"Error: {input_dir} does not exist. Run generate_ha_discovery.py first.", file=sys.stderr)
        sys.exit(1)

    # Check that at least one JSONL file exists
    jsonl_files = list(input_dir.glob('*.jsonl'))
    if not jsonl_files:
        print(f"Error: No JSONL files found in {input_dir}. Run generate_ha_discovery.py first.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(jsonl_files)} JSONL files in {input_dir}")

    # Generate header
    header = generate_header(input_dir)

    # Write output
    print(f"Writing compressed header to {output_file}")
    with open(output_file, 'w') as f:
        f.write(header)

    # Print summary
    total_compressed = 0
    total_uncompressed = 0
    for category in CATEGORIES:
        jsonl_path = input_dir / f'{category}.jsonl'
        if jsonl_path.exists():
            total_uncompressed += jsonl_path.stat().st_size
            compressed = compress_jsonl(jsonl_path)
            total_compressed += len(compressed)

    ratio = total_compressed / total_uncompressed * 100 if total_uncompressed else 0
    print(f"\nCompression summary:")
    print(f"  Total uncompressed: {total_uncompressed:,} bytes")
    print(f"  Total compressed:   {total_compressed:,} bytes")
    print(f"  Ratio: {ratio:.1f}%")
    print("Done!")


if __name__ == '__main__':
    main()
